// <auto-generated />
namespace CarShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ann_model_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ann_model_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202012011318430_ann_model_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
